language: elixir
elixir:
- 1.4.2
otp_release:
- 19.3
services:
- postgresql
addons:
  postgresql: '9.4'
before_script:
- psql -c 'create database advisor_test;' -U postgres
- psql -c 'create extension pgcrypto;' -U postgres
script:
- MIX_ENV=test mix ci
- MIX_ENV=test mix coveralls.travis
cache:
  directories:
  - _build
  - deps
  - otp
  - ".kerl"
deploy:
  provider: heroku
  app: advisorex
  on: master
  api_key:
    secure: jXUcSpZyBeEfb4yIoPjMqZ3AHB7W8nd7nvspmyuVzbaqdCegSvIEe4N5s11WjfT1qzV/8E+SsH2rep9IOmyeHlyrAfwgd3Ql0iWA9iQVS7iu3eXd9VMWUlVt8uZihu2HG3j3dDWMStywYRuq4ETHn13W2ylz977cySmj94mgb0ni4Hu7Wej1Z1l1EzM5aTpqCQ88HouchQLRgVUEpBJluoMq8bGEf8FF5EJASzee3MibKJiYZIqBHEDz+Cv7iGdoDwPI96j8x2JjFJohuhL0brKbivdO4HWL9QWn1WHFxYftW2rcaPlb+VCIuwCaKnwhKnJ2m5pHJGgvJlNbU5/ZA/TIxu1HYgkveUavCzwBfUp7fZj0NFkHq2EdGrGe7vuFFAkXFUo2q7DPkcN85S4w7gwP7TygXC0KsG2iyCOqM0Bisn/5HOorPlzhYFahFxgxychiIwT3/DCwKZpck2G5Mj394UyAZ1qitcIrmv5FqW7Sel0xB5T9ZVP44fPs7uQYZxhVbaTO7UTSBsN6ZmTMxZSksSwSWHt0Q16hO1x2+JgLv+xV2/eeDnhQBfajsBSdp999J2vQaOeaNfjH1GEGrym4E+ZRCIi3v9ie6DiEyQVu4rFMmzYsjB/WydG7OBaY6nMpT5C2F9apsBIQlpM4TN+Nov0shJzks0jZltD62EE=
