language: elixir
elixir:
- 1.4.2
otp_release:
- 19.3
services:
- postgresql
addons:
  postgresql: '9.4'
before_script:
- psql -c 'create database advisor_test;' -U postgres
- psql -c 'create extension pgcrypto;' -U postgres
script:
- MIX_ENV=test mix ci
- MIX_ENV=test mix coveralls.travis
cache:
  directories:
  - _build
  - deps
  - otp
  - ".kerl"
deploy:
  provider: heroku
  app: advisorex
  on: master
  api_key:
    secure: b4Js0xsNx0yCDKESgLH7K0JYv1F0TGyb5nxftelFuepmTIKrUQC8vkGPRHZ2eKiiq35Rz+gk5v73LBOM7n1rEaIjEhvbA/xMgN4n7+VXd37h4jhTpBpwwFPp850btsIx9uskkF5aVpUImE9EPtNyxpPFO4VDLquq69puBRauCW5iypQSlqCaAhOXs8abWkchR4LT0g+6SAg5Xw0FiTHEa7nhwXl673XZT1L6bvwRU+zWCxlYwTswqaFmVAWuOPLaGOWx24FCaHWKxj3Xl/VL0taQW4diuhKlaUx9u0mf2DKw2VTQnaEopPoX7GCi60SgBeGChs9oE42ZcoEJ+/0eNKNoX90vbV+4MYLONoo+iwd6k4ZlVmIgGkW8vHNNZqm5lQxJgHCoNq4vuAnEpfCEmdiQTzNyF2Rk2PREnsXN/eXyk+Gc1iohlYJUYg1u2ScmEV3gxXgbgwcWxbyn2G59oEZj8RnjbSvMN92VtlbEiffmcxRjIOERrqKSZgAVswCgU5okBn7NgD+XGKXmw14fQYe4krqr3rpFzPEGHmzVKXmO5KWg3fVpLXyd7oxYljwoCTAKAjEaox8PuG2C05GJOG6WVFqkhLRYW7dLC5ZFk4Djq10FqmeHlsCSmphi8It/zsRf62jXfe/mKwEF6qfZqcQP0H+CS92drapy4gR08JA=
