language: elixir
elixir:
- 1.8.0
otp_release:
- 20.3
services:
- postgresql
addons:
  postgresql: '9.4'
before_script:
- psql -c 'create database advisor_test;' -U postgres
- psql -c 'create extension pgcrypto;' -U postgres
script:
- MIX_ENV=test mix ci
- MIX_ENV=test mix coveralls.travis
cache:
  directories:
  - _build
  - deps
  - otp
  - ".kerl"
deploy:
  provider: heroku
  app: advisorex
  on: master
  api_key:
    secure: kBo7gjwqvZTS/9lK0rC/+mrtXwt0sMfXkhJYZIsaWdGE7wcemx+FK4/s1cAkhChVhYFZ8YotYdHlJxwveSfexfd+QzFx6yW1lgn+IgSxV0uGItJ4sHlsEokstF4GkGh1nx78RwEqRyz/PBwRBIKmq0y5P9bFUUliiTUYd+1+fIRFz+I9m7fudUI8x5BBXeiU4vngnRh64OP9giuj2sBlBmA7XuQfGWZ5Ipm8NMAGJQqc1Ig8+grtN4x6ULK1cvwZq6jhMbd2w1wquHReRnwAcFRfrUJ8ha9juiEvsOkOvNzPIZwsPXkvLCIPEvn9pFO7XIqyg0XBGhKcko9gVYrTbmiDzOs6XDF6MNOZbnpe6GeKxHx5XND72+BpRosoZEWUwtnAUK3Xvs6t2EW58sVsEDmuE9MBYKi/PgpX5PX+tDrp7DqOF7AyWBX4g5NEjTJXWmGO86+0oisu1d/qG6H1Agl56sMLZnXx5WpevNSLJ+0eHjeXBCebs0bUxRFfTLf5ELQbYfdWnKX+HMXTLiMHF6IhW2it7QQxrGTXDMRFnbqaQ/a8w4WK65OkeAWmVpLP3F+uefkAx89sIe8bTpBpzTI/ZZCre/ugiRk2PkwM1ScGL8B3X3FmokrcegRz53pJJsO8M/dGDIG4r4XHNSSg1DdA9avfFAANhkIWz2qjSnE=
